/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EstadoProcessoDTO
    /// </summary>
    [DataContract]
    public partial class EstadoProcessoDTO :  IEquatable<EstadoProcessoDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EstadoProcessoDTO" /> class.
        /// </summary>
        /// <param name="estadoProcesso">estadoProcesso.</param>
        /// <param name="descricaoEstadoProcesso">descricaoEstadoProcesso.</param>
        public EstadoProcessoDTO(long? estadoProcesso = default(long?), string descricaoEstadoProcesso = default(string))
        {
            this.EstadoProcesso = estadoProcesso;
            this.DescricaoEstadoProcesso = descricaoEstadoProcesso;
        }
        
        /// <summary>
        /// Gets or Sets EstadoProcesso
        /// </summary>
        [DataMember(Name="estadoProcesso", EmitDefaultValue=false)]
        public long? EstadoProcesso { get; set; }

        /// <summary>
        /// Gets or Sets DescricaoEstadoProcesso
        /// </summary>
        [DataMember(Name="descricaoEstadoProcesso", EmitDefaultValue=false)]
        public string DescricaoEstadoProcesso { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EstadoProcessoDTO {\n");
            sb.Append("  EstadoProcesso: ").Append(EstadoProcesso).Append("\n");
            sb.Append("  DescricaoEstadoProcesso: ").Append(DescricaoEstadoProcesso).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EstadoProcessoDTO);
        }

        /// <summary>
        /// Returns true if EstadoProcessoDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EstadoProcessoDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EstadoProcessoDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EstadoProcesso == input.EstadoProcesso ||
                    (this.EstadoProcesso != null &&
                    this.EstadoProcesso.Equals(input.EstadoProcesso))
                ) && 
                (
                    this.DescricaoEstadoProcesso == input.DescricaoEstadoProcesso ||
                    (this.DescricaoEstadoProcesso != null &&
                    this.DescricaoEstadoProcesso.Equals(input.DescricaoEstadoProcesso))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EstadoProcesso != null)
                    hashCode = hashCode * 59 + this.EstadoProcesso.GetHashCode();
                if (this.DescricaoEstadoProcesso != null)
                    hashCode = hashCode * 59 + this.DescricaoEstadoProcesso.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
