/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// EstadoProcesso
    /// </summary>
    [DataContract]
    public partial class EstadoProcesso :  IEquatable<EstadoProcesso>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EstadoProcesso" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EstadoProcesso() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EstadoProcesso" /> class.
        /// </summary>
        /// <param name="estadoProcesso">estadoProcesso (required).</param>
        /// <param name="descricaoEstadoProcesso">descricaoEstadoProcesso.</param>
        public EstadoProcesso(long? estadoProcesso = default(long?), string descricaoEstadoProcesso = default(string))
        {
            // to ensure "estadoProcesso" is required (not null)
            if (estadoProcesso == null)
            {
                throw new InvalidDataException("estadoProcesso is a required property for EstadoProcesso and cannot be null");
            }
            else
            {
                this._EstadoProcesso = estadoProcesso;
            }
            this.DescricaoEstadoProcesso = descricaoEstadoProcesso;
        }
        
        /// <summary>
        /// Gets or Sets _EstadoProcesso
        /// </summary>
        [DataMember(Name="estadoProcesso", EmitDefaultValue=false)]
        public long? _EstadoProcesso { get; set; }

        /// <summary>
        /// Gets or Sets DescricaoEstadoProcesso
        /// </summary>
        [DataMember(Name="descricaoEstadoProcesso", EmitDefaultValue=false)]
        public string DescricaoEstadoProcesso { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EstadoProcesso {\n");
            sb.Append("  _EstadoProcesso: ").Append(_EstadoProcesso).Append("\n");
            sb.Append("  DescricaoEstadoProcesso: ").Append(DescricaoEstadoProcesso).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EstadoProcesso);
        }

        /// <summary>
        /// Returns true if EstadoProcesso instances are equal
        /// </summary>
        /// <param name="input">Instance of EstadoProcesso to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EstadoProcesso input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._EstadoProcesso == input._EstadoProcesso ||
                    (this._EstadoProcesso != null &&
                    this._EstadoProcesso.Equals(input._EstadoProcesso))
                ) && 
                (
                    this.DescricaoEstadoProcesso == input.DescricaoEstadoProcesso ||
                    (this.DescricaoEstadoProcesso != null &&
                    this.DescricaoEstadoProcesso.Equals(input.DescricaoEstadoProcesso))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._EstadoProcesso != null)
                    hashCode = hashCode * 59 + this._EstadoProcesso.GetHashCode();
                if (this.DescricaoEstadoProcesso != null)
                    hashCode = hashCode * 59 + this.DescricaoEstadoProcesso.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DescricaoEstadoProcesso (string) maxLength
            if(this.DescricaoEstadoProcesso != null && this.DescricaoEstadoProcesso.Length > 30)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DescricaoEstadoProcesso, length must be less than 30.", new [] { "DescricaoEstadoProcesso" });
            }

            // DescricaoEstadoProcesso (string) minLength
            if(this.DescricaoEstadoProcesso != null && this.DescricaoEstadoProcesso.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DescricaoEstadoProcesso, length must be greater than 0.", new [] { "DescricaoEstadoProcesso" });
            }

            yield break;
        }
    }

}
