/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ParametroMovimentaTrocaClasseDTO
    /// </summary>
    [DataContract]
    public partial class ParametroMovimentaTrocaClasseDTO :  IEquatable<ParametroMovimentaTrocaClasseDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParametroMovimentaTrocaClasseDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ParametroMovimentaTrocaClasseDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ParametroMovimentaTrocaClasseDTO" /> class.
        /// </summary>
        /// <param name="etiquetaEnderecoOrigem">Etiqueta de endereço de origem onde o produto está. (required).</param>
        /// <param name="codigoUaOrigem">Código da unidade de armazenamento que representa o palette onde o produto está. (required).</param>
        /// <param name="etiquetaEnderecoDestino">Etiqueta de endereço de destino para onde o produto será transferido. (required).</param>
        /// <param name="classeOrigem">Classe atual ao qual o produto está sendo representado (required).</param>
        /// <param name="classeDestino">Será a classe de destino do produto após a movimentação de endereço e troca da classe origem pela destino (required).</param>
        public ParametroMovimentaTrocaClasseDTO(string etiquetaEnderecoOrigem = default(string), long? codigoUaOrigem = default(long?), string etiquetaEnderecoDestino = default(string), string classeOrigem = default(string), string classeDestino = default(string))
        {
            // to ensure "etiquetaEnderecoOrigem" is required (not null)
            if (etiquetaEnderecoOrigem == null)
            {
                throw new InvalidDataException("etiquetaEnderecoOrigem is a required property for ParametroMovimentaTrocaClasseDTO and cannot be null");
            }
            else
            {
                this.EtiquetaEnderecoOrigem = etiquetaEnderecoOrigem;
            }
            // to ensure "codigoUaOrigem" is required (not null)
            if (codigoUaOrigem == null)
            {
                throw new InvalidDataException("codigoUaOrigem is a required property for ParametroMovimentaTrocaClasseDTO and cannot be null");
            }
            else
            {
                this.CodigoUaOrigem = codigoUaOrigem;
            }
            // to ensure "etiquetaEnderecoDestino" is required (not null)
            if (etiquetaEnderecoDestino == null)
            {
                throw new InvalidDataException("etiquetaEnderecoDestino is a required property for ParametroMovimentaTrocaClasseDTO and cannot be null");
            }
            else
            {
                this.EtiquetaEnderecoDestino = etiquetaEnderecoDestino;
            }
            // to ensure "classeOrigem" is required (not null)
            if (classeOrigem == null)
            {
                throw new InvalidDataException("classeOrigem is a required property for ParametroMovimentaTrocaClasseDTO and cannot be null");
            }
            else
            {
                this.ClasseOrigem = classeOrigem;
            }
            // to ensure "classeDestino" is required (not null)
            if (classeDestino == null)
            {
                throw new InvalidDataException("classeDestino is a required property for ParametroMovimentaTrocaClasseDTO and cannot be null");
            }
            else
            {
                this.ClasseDestino = classeDestino;
            }
        }
        
        /// <summary>
        /// Etiqueta de endereço de origem onde o produto está.
        /// </summary>
        /// <value>Etiqueta de endereço de origem onde o produto está.</value>
        [DataMember(Name="etiquetaEnderecoOrigem", EmitDefaultValue=false)]
        public string EtiquetaEnderecoOrigem { get; set; }

        /// <summary>
        /// Código da unidade de armazenamento que representa o palette onde o produto está.
        /// </summary>
        /// <value>Código da unidade de armazenamento que representa o palette onde o produto está.</value>
        [DataMember(Name="codigoUaOrigem", EmitDefaultValue=false)]
        public long? CodigoUaOrigem { get; set; }

        /// <summary>
        /// Etiqueta de endereço de destino para onde o produto será transferido.
        /// </summary>
        /// <value>Etiqueta de endereço de destino para onde o produto será transferido.</value>
        [DataMember(Name="etiquetaEnderecoDestino", EmitDefaultValue=false)]
        public string EtiquetaEnderecoDestino { get; set; }

        /// <summary>
        /// Classe atual ao qual o produto está sendo representado
        /// </summary>
        /// <value>Classe atual ao qual o produto está sendo representado</value>
        [DataMember(Name="classeOrigem", EmitDefaultValue=false)]
        public string ClasseOrigem { get; set; }

        /// <summary>
        /// Será a classe de destino do produto após a movimentação de endereço e troca da classe origem pela destino
        /// </summary>
        /// <value>Será a classe de destino do produto após a movimentação de endereço e troca da classe origem pela destino</value>
        [DataMember(Name="classeDestino", EmitDefaultValue=false)]
        public string ClasseDestino { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParametroMovimentaTrocaClasseDTO {\n");
            sb.Append("  EtiquetaEnderecoOrigem: ").Append(EtiquetaEnderecoOrigem).Append("\n");
            sb.Append("  CodigoUaOrigem: ").Append(CodigoUaOrigem).Append("\n");
            sb.Append("  EtiquetaEnderecoDestino: ").Append(EtiquetaEnderecoDestino).Append("\n");
            sb.Append("  ClasseOrigem: ").Append(ClasseOrigem).Append("\n");
            sb.Append("  ClasseDestino: ").Append(ClasseDestino).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParametroMovimentaTrocaClasseDTO);
        }

        /// <summary>
        /// Returns true if ParametroMovimentaTrocaClasseDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ParametroMovimentaTrocaClasseDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParametroMovimentaTrocaClasseDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EtiquetaEnderecoOrigem == input.EtiquetaEnderecoOrigem ||
                    (this.EtiquetaEnderecoOrigem != null &&
                    this.EtiquetaEnderecoOrigem.Equals(input.EtiquetaEnderecoOrigem))
                ) && 
                (
                    this.CodigoUaOrigem == input.CodigoUaOrigem ||
                    (this.CodigoUaOrigem != null &&
                    this.CodigoUaOrigem.Equals(input.CodigoUaOrigem))
                ) && 
                (
                    this.EtiquetaEnderecoDestino == input.EtiquetaEnderecoDestino ||
                    (this.EtiquetaEnderecoDestino != null &&
                    this.EtiquetaEnderecoDestino.Equals(input.EtiquetaEnderecoDestino))
                ) && 
                (
                    this.ClasseOrigem == input.ClasseOrigem ||
                    (this.ClasseOrigem != null &&
                    this.ClasseOrigem.Equals(input.ClasseOrigem))
                ) && 
                (
                    this.ClasseDestino == input.ClasseDestino ||
                    (this.ClasseDestino != null &&
                    this.ClasseDestino.Equals(input.ClasseDestino))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EtiquetaEnderecoOrigem != null)
                    hashCode = hashCode * 59 + this.EtiquetaEnderecoOrigem.GetHashCode();
                if (this.CodigoUaOrigem != null)
                    hashCode = hashCode * 59 + this.CodigoUaOrigem.GetHashCode();
                if (this.EtiquetaEnderecoDestino != null)
                    hashCode = hashCode * 59 + this.EtiquetaEnderecoDestino.GetHashCode();
                if (this.ClasseOrigem != null)
                    hashCode = hashCode * 59 + this.ClasseOrigem.GetHashCode();
                if (this.ClasseDestino != null)
                    hashCode = hashCode * 59 + this.ClasseDestino.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EtiquetaEnderecoOrigem (string) maxLength
            if(this.EtiquetaEnderecoOrigem != null && this.EtiquetaEnderecoOrigem.Length > 15)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EtiquetaEnderecoOrigem, length must be less than 15.", new [] { "EtiquetaEnderecoOrigem" });
            }

            // EtiquetaEnderecoOrigem (string) minLength
            if(this.EtiquetaEnderecoOrigem != null && this.EtiquetaEnderecoOrigem.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EtiquetaEnderecoOrigem, length must be greater than 0.", new [] { "EtiquetaEnderecoOrigem" });
            }

            // EtiquetaEnderecoDestino (string) maxLength
            if(this.EtiquetaEnderecoDestino != null && this.EtiquetaEnderecoDestino.Length > 15)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EtiquetaEnderecoDestino, length must be less than 15.", new [] { "EtiquetaEnderecoDestino" });
            }

            // EtiquetaEnderecoDestino (string) minLength
            if(this.EtiquetaEnderecoDestino != null && this.EtiquetaEnderecoDestino.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EtiquetaEnderecoDestino, length must be greater than 0.", new [] { "EtiquetaEnderecoDestino" });
            }

            // ClasseOrigem (string) maxLength
            if(this.ClasseOrigem != null && this.ClasseOrigem.Length > 5)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ClasseOrigem, length must be less than 5.", new [] { "ClasseOrigem" });
            }

            // ClasseOrigem (string) minLength
            if(this.ClasseOrigem != null && this.ClasseOrigem.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ClasseOrigem, length must be greater than 0.", new [] { "ClasseOrigem" });
            }

            // ClasseDestino (string) maxLength
            if(this.ClasseDestino != null && this.ClasseDestino.Length > 5)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ClasseDestino, length must be less than 5.", new [] { "ClasseDestino" });
            }

            // ClasseDestino (string) minLength
            if(this.ClasseDestino != null && this.ClasseDestino.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ClasseDestino, length must be greater than 0.", new [] { "ClasseDestino" });
            }

            yield break;
        }
    }

}
