/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PublicoAlvoDTO
    /// </summary>
    [DataContract]
    public partial class PublicoAlvoDTO :  IEquatable<PublicoAlvoDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicoAlvoDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicoAlvoDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicoAlvoDTO" /> class.
        /// </summary>
        /// <param name="codigoPublicoAlvo">Publico Alvo, caso não exista será cadastrado (required).</param>
        /// <param name="descricaoPublicoAlvo">Descrição do Publico Alvo do Produto (required).</param>
        public PublicoAlvoDTO(string codigoPublicoAlvo = default(string), string descricaoPublicoAlvo = default(string))
        {
            // to ensure "codigoPublicoAlvo" is required (not null)
            if (codigoPublicoAlvo == null)
            {
                throw new InvalidDataException("codigoPublicoAlvo is a required property for PublicoAlvoDTO and cannot be null");
            }
            else
            {
                this.CodigoPublicoAlvo = codigoPublicoAlvo;
            }
            // to ensure "descricaoPublicoAlvo" is required (not null)
            if (descricaoPublicoAlvo == null)
            {
                throw new InvalidDataException("descricaoPublicoAlvo is a required property for PublicoAlvoDTO and cannot be null");
            }
            else
            {
                this.DescricaoPublicoAlvo = descricaoPublicoAlvo;
            }
        }
        
        /// <summary>
        /// Publico Alvo, caso não exista será cadastrado
        /// </summary>
        /// <value>Publico Alvo, caso não exista será cadastrado</value>
        [DataMember(Name="codigoPublicoAlvo", EmitDefaultValue=false)]
        public string CodigoPublicoAlvo { get; set; }

        /// <summary>
        /// Descrição do Publico Alvo do Produto
        /// </summary>
        /// <value>Descrição do Publico Alvo do Produto</value>
        [DataMember(Name="descricaoPublicoAlvo", EmitDefaultValue=false)]
        public string DescricaoPublicoAlvo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublicoAlvoDTO {\n");
            sb.Append("  CodigoPublicoAlvo: ").Append(CodigoPublicoAlvo).Append("\n");
            sb.Append("  DescricaoPublicoAlvo: ").Append(DescricaoPublicoAlvo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PublicoAlvoDTO);
        }

        /// <summary>
        /// Returns true if PublicoAlvoDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of PublicoAlvoDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublicoAlvoDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CodigoPublicoAlvo == input.CodigoPublicoAlvo ||
                    (this.CodigoPublicoAlvo != null &&
                    this.CodigoPublicoAlvo.Equals(input.CodigoPublicoAlvo))
                ) && 
                (
                    this.DescricaoPublicoAlvo == input.DescricaoPublicoAlvo ||
                    (this.DescricaoPublicoAlvo != null &&
                    this.DescricaoPublicoAlvo.Equals(input.DescricaoPublicoAlvo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CodigoPublicoAlvo != null)
                    hashCode = hashCode * 59 + this.CodigoPublicoAlvo.GetHashCode();
                if (this.DescricaoPublicoAlvo != null)
                    hashCode = hashCode * 59 + this.DescricaoPublicoAlvo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CodigoPublicoAlvo (string) maxLength
            if(this.CodigoPublicoAlvo != null && this.CodigoPublicoAlvo.Length > 25)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CodigoPublicoAlvo, length must be less than 25.", new [] { "CodigoPublicoAlvo" });
            }

            // CodigoPublicoAlvo (string) minLength
            if(this.CodigoPublicoAlvo != null && this.CodigoPublicoAlvo.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CodigoPublicoAlvo, length must be greater than 1.", new [] { "CodigoPublicoAlvo" });
            }

            // DescricaoPublicoAlvo (string) maxLength
            if(this.DescricaoPublicoAlvo != null && this.DescricaoPublicoAlvo.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DescricaoPublicoAlvo, length must be less than 100.", new [] { "DescricaoPublicoAlvo" });
            }

            // DescricaoPublicoAlvo (string) minLength
            if(this.DescricaoPublicoAlvo != null && this.DescricaoPublicoAlvo.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DescricaoPublicoAlvo, length must be greater than 1.", new [] { "DescricaoPublicoAlvo" });
            }

            yield break;
        }
    }

}
