/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SubGrupo
    /// </summary>
    [DataContract]
    public partial class SubGrupo :  IEquatable<SubGrupo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubGrupo" /> class.
        /// </summary>
        /// <param name="codigoSubGrupo">codigoSubGrupo.</param>
        /// <param name="descricaoSubGrupo">descricaoSubGrupo.</param>
        public SubGrupo(string codigoSubGrupo = default(string), string descricaoSubGrupo = default(string))
        {
            this.CodigoSubGrupo = codigoSubGrupo;
            this.DescricaoSubGrupo = descricaoSubGrupo;
        }
        
        /// <summary>
        /// Gets or Sets CodigoSubGrupo
        /// </summary>
        [DataMember(Name="codigoSubGrupo", EmitDefaultValue=false)]
        public string CodigoSubGrupo { get; set; }

        /// <summary>
        /// Gets or Sets DescricaoSubGrupo
        /// </summary>
        [DataMember(Name="descricaoSubGrupo", EmitDefaultValue=false)]
        public string DescricaoSubGrupo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubGrupo {\n");
            sb.Append("  CodigoSubGrupo: ").Append(CodigoSubGrupo).Append("\n");
            sb.Append("  DescricaoSubGrupo: ").Append(DescricaoSubGrupo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubGrupo);
        }

        /// <summary>
        /// Returns true if SubGrupo instances are equal
        /// </summary>
        /// <param name="input">Instance of SubGrupo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubGrupo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CodigoSubGrupo == input.CodigoSubGrupo ||
                    (this.CodigoSubGrupo != null &&
                    this.CodigoSubGrupo.Equals(input.CodigoSubGrupo))
                ) && 
                (
                    this.DescricaoSubGrupo == input.DescricaoSubGrupo ||
                    (this.DescricaoSubGrupo != null &&
                    this.DescricaoSubGrupo.Equals(input.DescricaoSubGrupo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CodigoSubGrupo != null)
                    hashCode = hashCode * 59 + this.CodigoSubGrupo.GetHashCode();
                if (this.DescricaoSubGrupo != null)
                    hashCode = hashCode * 59 + this.DescricaoSubGrupo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
