/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TipoUcDTO
    /// </summary>
    [DataContract]
    public partial class TipoUcDTO :  IEquatable<TipoUcDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TipoUcDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TipoUcDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TipoUcDTO" /> class.
        /// </summary>
        /// <param name="codigoEmpresa">codigoEmpresa.</param>
        /// <param name="codigoProduto">codigoProduto.</param>
        /// <param name="produto">produto.</param>
        /// <param name="tipoUc">Tipo UC do produto (required).</param>
        /// <param name="descricaoTipoUc">Descrição Tipo UC do produto (required).</param>
        /// <param name="fatorTipoUc">Descrição Tipo UC do produto (required).</param>
        /// <param name="padrao">padrao.</param>
        /// <param name="ativo">ativo.</param>
        /// <param name="usuario">usuario.</param>
        /// <param name="dataAtualizacao">dataAtualizacao.</param>
        /// <param name="produtoRelacionado">produtoRelacionado.</param>
        public TipoUcDTO(string codigoEmpresa = default(string), string codigoProduto = default(string), ProdutoDTO produto = default(ProdutoDTO), string tipoUc = default(string), string descricaoTipoUc = default(string), decimal? fatorTipoUc = default(decimal?), bool? padrao = default(bool?), bool? ativo = default(bool?), string usuario = default(string), DateTime? dataAtualizacao = default(DateTime?), List<ProdutoRelacionadoDTO> produtoRelacionado = default(List<ProdutoRelacionadoDTO>))
        {
            // to ensure "tipoUc" is required (not null)
            if (tipoUc == null)
            {
                throw new InvalidDataException("tipoUc is a required property for TipoUcDTO and cannot be null");
            }
            else
            {
                this.TipoUc = tipoUc;
            }
            // to ensure "descricaoTipoUc" is required (not null)
            if (descricaoTipoUc == null)
            {
                throw new InvalidDataException("descricaoTipoUc is a required property for TipoUcDTO and cannot be null");
            }
            else
            {
                this.DescricaoTipoUc = descricaoTipoUc;
            }
            // to ensure "fatorTipoUc" is required (not null)
            if (fatorTipoUc == null)
            {
                throw new InvalidDataException("fatorTipoUc is a required property for TipoUcDTO and cannot be null");
            }
            else
            {
                this.FatorTipoUc = fatorTipoUc;
            }
            this.CodigoEmpresa = codigoEmpresa;
            this.CodigoProduto = codigoProduto;
            this.Produto = produto;
            this.Padrao = padrao;
            this.Ativo = ativo;
            this.Usuario = usuario;
            this.DataAtualizacao = dataAtualizacao;
            this.ProdutoRelacionado = produtoRelacionado;
        }
        
        /// <summary>
        /// Gets or Sets CodigoEmpresa
        /// </summary>
        [DataMember(Name="codigoEmpresa", EmitDefaultValue=false)]
        public string CodigoEmpresa { get; set; }

        /// <summary>
        /// Gets or Sets CodigoProduto
        /// </summary>
        [DataMember(Name="codigoProduto", EmitDefaultValue=false)]
        public string CodigoProduto { get; set; }

        /// <summary>
        /// Gets or Sets Produto
        /// </summary>
        [DataMember(Name="produto", EmitDefaultValue=false)]
        public ProdutoDTO Produto { get; set; }

        /// <summary>
        /// Tipo UC do produto
        /// </summary>
        /// <value>Tipo UC do produto</value>
        [DataMember(Name="tipoUc", EmitDefaultValue=false)]
        public string TipoUc { get; set; }

        /// <summary>
        /// Descrição Tipo UC do produto
        /// </summary>
        /// <value>Descrição Tipo UC do produto</value>
        [DataMember(Name="descricaoTipoUc", EmitDefaultValue=false)]
        public string DescricaoTipoUc { get; set; }

        /// <summary>
        /// Descrição Tipo UC do produto
        /// </summary>
        /// <value>Descrição Tipo UC do produto</value>
        [DataMember(Name="fatorTipoUc", EmitDefaultValue=false)]
        public decimal? FatorTipoUc { get; set; }

        /// <summary>
        /// Gets or Sets Padrao
        /// </summary>
        [DataMember(Name="padrao", EmitDefaultValue=false)]
        public bool? Padrao { get; set; }

        /// <summary>
        /// Gets or Sets Ativo
        /// </summary>
        [DataMember(Name="ativo", EmitDefaultValue=false)]
        public bool? Ativo { get; set; }

        /// <summary>
        /// Gets or Sets Usuario
        /// </summary>
        [DataMember(Name="usuario", EmitDefaultValue=false)]
        public string Usuario { get; set; }

        /// <summary>
        /// Gets or Sets DataAtualizacao
        /// </summary>
        [DataMember(Name="dataAtualizacao", EmitDefaultValue=false)]
        public DateTime? DataAtualizacao { get; set; }

        /// <summary>
        /// Gets or Sets ProdutoRelacionado
        /// </summary>
        [DataMember(Name="produtoRelacionado", EmitDefaultValue=false)]
        public List<ProdutoRelacionadoDTO> ProdutoRelacionado { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TipoUcDTO {\n");
            sb.Append("  CodigoEmpresa: ").Append(CodigoEmpresa).Append("\n");
            sb.Append("  CodigoProduto: ").Append(CodigoProduto).Append("\n");
            sb.Append("  Produto: ").Append(Produto).Append("\n");
            sb.Append("  TipoUc: ").Append(TipoUc).Append("\n");
            sb.Append("  DescricaoTipoUc: ").Append(DescricaoTipoUc).Append("\n");
            sb.Append("  FatorTipoUc: ").Append(FatorTipoUc).Append("\n");
            sb.Append("  Padrao: ").Append(Padrao).Append("\n");
            sb.Append("  Ativo: ").Append(Ativo).Append("\n");
            sb.Append("  Usuario: ").Append(Usuario).Append("\n");
            sb.Append("  DataAtualizacao: ").Append(DataAtualizacao).Append("\n");
            sb.Append("  ProdutoRelacionado: ").Append(ProdutoRelacionado).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TipoUcDTO);
        }

        /// <summary>
        /// Returns true if TipoUcDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of TipoUcDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TipoUcDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CodigoEmpresa == input.CodigoEmpresa ||
                    (this.CodigoEmpresa != null &&
                    this.CodigoEmpresa.Equals(input.CodigoEmpresa))
                ) && 
                (
                    this.CodigoProduto == input.CodigoProduto ||
                    (this.CodigoProduto != null &&
                    this.CodigoProduto.Equals(input.CodigoProduto))
                ) && 
                (
                    this.Produto == input.Produto ||
                    (this.Produto != null &&
                    this.Produto.Equals(input.Produto))
                ) && 
                (
                    this.TipoUc == input.TipoUc ||
                    (this.TipoUc != null &&
                    this.TipoUc.Equals(input.TipoUc))
                ) && 
                (
                    this.DescricaoTipoUc == input.DescricaoTipoUc ||
                    (this.DescricaoTipoUc != null &&
                    this.DescricaoTipoUc.Equals(input.DescricaoTipoUc))
                ) && 
                (
                    this.FatorTipoUc == input.FatorTipoUc ||
                    (this.FatorTipoUc != null &&
                    this.FatorTipoUc.Equals(input.FatorTipoUc))
                ) && 
                (
                    this.Padrao == input.Padrao ||
                    (this.Padrao != null &&
                    this.Padrao.Equals(input.Padrao))
                ) && 
                (
                    this.Ativo == input.Ativo ||
                    (this.Ativo != null &&
                    this.Ativo.Equals(input.Ativo))
                ) && 
                (
                    this.Usuario == input.Usuario ||
                    (this.Usuario != null &&
                    this.Usuario.Equals(input.Usuario))
                ) && 
                (
                    this.DataAtualizacao == input.DataAtualizacao ||
                    (this.DataAtualizacao != null &&
                    this.DataAtualizacao.Equals(input.DataAtualizacao))
                ) && 
                (
                    this.ProdutoRelacionado == input.ProdutoRelacionado ||
                    this.ProdutoRelacionado != null &&
                    this.ProdutoRelacionado.SequenceEqual(input.ProdutoRelacionado)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CodigoEmpresa != null)
                    hashCode = hashCode * 59 + this.CodigoEmpresa.GetHashCode();
                if (this.CodigoProduto != null)
                    hashCode = hashCode * 59 + this.CodigoProduto.GetHashCode();
                if (this.Produto != null)
                    hashCode = hashCode * 59 + this.Produto.GetHashCode();
                if (this.TipoUc != null)
                    hashCode = hashCode * 59 + this.TipoUc.GetHashCode();
                if (this.DescricaoTipoUc != null)
                    hashCode = hashCode * 59 + this.DescricaoTipoUc.GetHashCode();
                if (this.FatorTipoUc != null)
                    hashCode = hashCode * 59 + this.FatorTipoUc.GetHashCode();
                if (this.Padrao != null)
                    hashCode = hashCode * 59 + this.Padrao.GetHashCode();
                if (this.Ativo != null)
                    hashCode = hashCode * 59 + this.Ativo.GetHashCode();
                if (this.Usuario != null)
                    hashCode = hashCode * 59 + this.Usuario.GetHashCode();
                if (this.DataAtualizacao != null)
                    hashCode = hashCode * 59 + this.DataAtualizacao.GetHashCode();
                if (this.ProdutoRelacionado != null)
                    hashCode = hashCode * 59 + this.ProdutoRelacionado.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
