/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TipoBaixa
    /// </summary>
    [DataContract]
    public partial class TipoBaixa :  IEquatable<TipoBaixa>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TipoBaixa" /> class.
        /// </summary>
        /// <param name="tipoBaixa">tipoBaixa.</param>
        /// <param name="descricaoTipoBaixa">descricaoTipoBaixa.</param>
        public TipoBaixa(long? tipoBaixa = default(long?), string descricaoTipoBaixa = default(string))
        {
            this._TipoBaixa = tipoBaixa;
            this.DescricaoTipoBaixa = descricaoTipoBaixa;
        }
        
        /// <summary>
        /// Gets or Sets _TipoBaixa
        /// </summary>
        [DataMember(Name="tipoBaixa", EmitDefaultValue=false)]
        public long? _TipoBaixa { get; set; }

        /// <summary>
        /// Gets or Sets DescricaoTipoBaixa
        /// </summary>
        [DataMember(Name="descricaoTipoBaixa", EmitDefaultValue=false)]
        public string DescricaoTipoBaixa { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TipoBaixa {\n");
            sb.Append("  _TipoBaixa: ").Append(_TipoBaixa).Append("\n");
            sb.Append("  DescricaoTipoBaixa: ").Append(DescricaoTipoBaixa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TipoBaixa);
        }

        /// <summary>
        /// Returns true if TipoBaixa instances are equal
        /// </summary>
        /// <param name="input">Instance of TipoBaixa to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TipoBaixa input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._TipoBaixa == input._TipoBaixa ||
                    (this._TipoBaixa != null &&
                    this._TipoBaixa.Equals(input._TipoBaixa))
                ) && 
                (
                    this.DescricaoTipoBaixa == input.DescricaoTipoBaixa ||
                    (this.DescricaoTipoBaixa != null &&
                    this.DescricaoTipoBaixa.Equals(input.DescricaoTipoBaixa))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._TipoBaixa != null)
                    hashCode = hashCode * 59 + this._TipoBaixa.GetHashCode();
                if (this.DescricaoTipoBaixa != null)
                    hashCode = hashCode * 59 + this.DescricaoTipoBaixa.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
