/* 
 * Zion WMS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// UnidadeFederativaDTO
    /// </summary>
    [DataContract]
    public partial class UnidadeFederativaDTO :  IEquatable<UnidadeFederativaDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnidadeFederativaDTO" /> class.
        /// </summary>
        /// <param name="uf">uf.</param>
        /// <param name="descricaoUf">descricaoUf.</param>
        public UnidadeFederativaDTO(string uf = default(string), string descricaoUf = default(string))
        {
            this.Uf = uf;
            this.DescricaoUf = descricaoUf;
        }
        
        /// <summary>
        /// Gets or Sets Uf
        /// </summary>
        [DataMember(Name="uf", EmitDefaultValue=false)]
        public string Uf { get; set; }

        /// <summary>
        /// Gets or Sets DescricaoUf
        /// </summary>
        [DataMember(Name="descricaoUf", EmitDefaultValue=false)]
        public string DescricaoUf { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UnidadeFederativaDTO {\n");
            sb.Append("  Uf: ").Append(Uf).Append("\n");
            sb.Append("  DescricaoUf: ").Append(DescricaoUf).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UnidadeFederativaDTO);
        }

        /// <summary>
        /// Returns true if UnidadeFederativaDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of UnidadeFederativaDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UnidadeFederativaDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Uf == input.Uf ||
                    (this.Uf != null &&
                    this.Uf.Equals(input.Uf))
                ) && 
                (
                    this.DescricaoUf == input.DescricaoUf ||
                    (this.DescricaoUf != null &&
                    this.DescricaoUf.Equals(input.DescricaoUf))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Uf != null)
                    hashCode = hashCode * 59 + this.Uf.GetHashCode();
                if (this.DescricaoUf != null)
                    hashCode = hashCode * 59 + this.DescricaoUf.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
